#Savegame properties
#Sun May 03 18:42:10 PST 2026
ammo=4
blockUnlocked=true
dashUnlocked=true
doubleJumpUnlocked=true
fragmentCount=2
gunUnlocked=true
immortalityUnlocked=true
introPlayed=true
levelIndex=1
untargetableUnlocked=true
