#Savegame properties
#Tue Dec 09 17:26:08 PST 2025
ammo=10
blockUnlocked=false
dashUnlocked=false
doubleJumpUnlocked=false
fragmentCount=0
gunUnlocked=false
immortalityUnlocked=false
introPlayed=true
levelIndex=0
untargetableUnlocked=false
