#Savegame properties
#Tue Dec 09 11:24:32 PST 2025
blockUnlocked=false
dashUnlocked=false
doubleJumpUnlocked=false
fragmentCount=0
gunUnlocked=false
immortalityUnlocked=false
introPlayed=false
levelIndex=0
untargetableUnlocked=false